In [10]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
#from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [11]:
d=pd.read_excel("C:\\Users\\ROHINI\\Desktop\\KCE-AI & ML\\Demo\\Bayesian\\Bayes-Flu.xlsx")
d=np.asarray(d)
print(d.shape)
X=d[:,0:3]
Y=d[:,3]

(8, 4)


In [12]:
print(X)
print(Y)

[[1 1 1]
 [2 1 2]
 [2 2 2]
 [1 2 1]
 [2 2 1]
 [2 1 2]
 [1 2 2]
 [1 2 1]]
[0 1 1 0 1 1 0 0]


In [13]:
r=MultinomialNB()
#r=GaussianNB()
r=r.fit(X,Y)

In [15]:
print(r.class_count_)
print(r.classes_)
predict_Y=r.predict(X)
print(predict_Y)
print('Accuracy',accuracy_score(Y,predict_Y)*100)
print('CM',confusion_matrix(Y,predict_Y))

[4. 4.]
[0 1]
[1 1 1 0 1 1 0 0]
Accuracy 87.5
CM [[3 1]
 [0 4]]
